# Generated by Django 4.2.13 on 2026-04-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='merchants_l_merchan_14aff4_idx',
            old_name='merchants_l_merchan_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='merchants_l_referen_fed3f6_idx',
            old_name='merchants_l_ref_id_idx',
        ),
    ]
