# Generated by Django 4.2.13 on 2026-04-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_pay_merchan_9a626f_idx',
            old_name='payouts_pay_merchant_status_idx',
        ),
    ]
